# Generated by Django 5.1.2 on 2024-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('reporter', models.CharField(max_length=200)),
            ],
        ),
    ]
