# Generated by Django 5.1.2 on 2024-10-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('principal', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(choices=[('u', 'unec'), ('h', 'his grace'), ('c', 'cic'), ('co', 'command')], max_length=200)),
            ],
        ),
    ]
